development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: sqlite3
  database: /home/cvzprj/mailbox_tester/shared/database/production.sqlite3
  pool: 5
  timeout: 5000

acceptatie_database:
  adapter: sqlserver
  host: CVZMDSA001
  port: 63420
  database: postbus
  username: bop_adm
  password: bop_adm

productie_database:
  adapter: mysql2
  encoding: utf8
  host: CVZLDMP001
  database: cvz_portal_services
  pool: 5
  username: cvz_prj_readonly
  password: R34dOnlyP